version: 2.1
executors:
  golang:
    docker:
      - image: cimg/go:1.19.2
    working_directory: /home/circleci/go/src/github.com/shibataka000/go-get-release
jobs:
  build:
    executor:
      name: golang
    steps:
      - checkout
      - run:
          name: Setup
          command: make setup
      - run:
          name: Run tests
          command: make ci
workflows:
  build:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
